package com.offermanager.inflight;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RulesDto implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public RulesDto() {
    }




}